### ISSUE TITLE
Update flutter

### ISSUE THREAD

**Issue by Nikarous** [MobileDevOps/flutter-sdk-image#6]
Hi, 

flutter version is very old. Could you upgrade it? I can make pull request if given permissions.

**Comment by messeb** [comment]
The image is updated to the latest version `1.22.5`, and a run of the [MobileDevOps/flutter-ci-demo](https://github.com/MobileDevOps/flutter-ci-demo) also works. ([Travis CI build](https://travis-ci.org/github/MobileDevOps/flutter-ci-demo/builds/750937766))

**Comment by devsideal** [comment]
Again outdated, Are you planning to update it to the latest flutter SDK?

**Comment by messeb** [comment]
Updated!

**Comment by enzo-santos** [comment]
Hi @messeb, thanks for this wonderful tool!

Could you please update it to the latest Flutter version (3.13.4)?
